name: Linux Container Node Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.REGISTRY_IMAGENAME }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/${IMAGE_NAME}:${GITHUB_REF#refs/heads/}
          docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/${IMAGE_NAME}:${GITHUB_REF#refs/heads/}
